apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: prod-ns

patches:
- path: deployment-prod.yaml
- path: service-prod.yaml

namePrefix: prod-
nameSuffix: -beta